### ISSUE TITLE
other options for transferring data?

### ISSUE THREAD

**Issue by grahamlopez** [olcf/olcf-user-docs#103]
Right now, the "Transferring Data" page only describes Globus. Should we have instructions about using command-line utilities with the DTNs, and/or other methods?

**Comment by gmarkomanolis** [comment]
I thought that but we have one filesystem anymore, what should be the source or destination? DTNs are for HPSS commands mainly now and Globus. External storage should be another center/user's storage etc.

**Comment by grahamlopez** [comment]
I was thinking of things like `scp`, `rsync`, dos and don'ts of staging through nfs/gpfs, etc. What are the other methods that we recommend?

**Comment by grahamlopez** [comment]
I was mainly thinking of transferring data into/out of OLCF, not between systems.

**Comment by gmarkomanolis** [comment]
yeah, ok we could add some stuff, nfs, overall should be avoided, I could test it. We have some text for in/out from OLCF systems with Globus personal only this moment.

**Comment by grahamlopez** [comment]
closed by #110
