### ISSUE TITLE
Move Home/DTNs/HPSS into Systems Section

### ISSUE THREAD

**Issue by jack-morrison** [olcf/olcf-user-docs#127]
Ideally, all of the systems an OLCF user may want to access are documented in a single place. Only some of these systems have full 'User Guides'.

This issue proposes removing the [`Systems Available to All Projects`](https://docs.olcf.ornl.gov/connecting/index.html#systems-available-to-all-projects) section, and adding `Home`/`DTNs`/`HPSS` under the [`Systems`](https://docs.olcf.ornl.gov/systems/index.html) section. This creates a single list where all host accesses are documented.

- [x] Home
- [x] DTNs
- [x] HPSS
- [x] Ascent

**Comment by grahamlopez** [comment]
Big "yes." Also DTNs as well (since you can log into them).

Ascent for consistency?

**Comment by jack-morrison** [comment]
(+ DTNS/HPSS, -Hub. My mistake.)

Agreed. I've added Ascent.
