### ISSUE TITLE
reroute olcf.ornl.gov navigation to RTD docs

### ISSUE THREAD

**Issue by grahamlopez** [olcf/olcf-user-docs#16]
The (non-documentation) navigation at olcf.ornl.gov needs to point to the RTD docs.

**Comment by jack-morrison** [comment]
- [ ] Header navigation ("For Users")
- [ ] "Computing at the OLCF" links (left side, mid way down on home page)
- [ ] Links to User Guides in ["Compute Systems"](https://www.olcf.ornl.gov/olcf-resources/compute-systems/) section
