### ISSUE TITLE
Add link to IBM WML CE talk by IBM

### ISSUE THREAD

**Issue by jack-morrison** [olcf/olcf-user-docs#165]
The recent talk given by Bryant Nelson (@bethune-bryant) and Brad Nemanich (@bnemanich) of IBM for the OLCF Monthly User Conference Call is now live here: [Distributed Deep Learning on Summit](https://vimeo.com/377551223).

This video should be embedded (or at least linked) from the Software > IBM WML CE page.

**Comment by warenaud** [comment]
The slides have also been uploaded. We may want to link those as well similar to the way we do on the event page (https://www.olcf.ornl.gov/calendar/userconcall-oct2019/)

**Comment by grahamlopez** [comment]
yeah, so far these videos/slides aren't being posted here to this site. This is really up to @tom-papatheodore when he wants to change this. Right now all we do is link to the batch at https://docs.olcf.ornl.gov/training/index.html

**Comment by tom-papatheodore** [comment]
I think there are 2 points here:

1) As Jack said, we should be pointing to specific training events in-line from within the OLCF docs where it makes sense. This could mean pointing to the actual event page, which (for now) will still need to live on the olcf site, or it could mean just pointing to specific slides and recordings, which live on the olcf site and vimeo, respectively. 

2) As Graham said, most of the training pages (aside from the calendar) can be moved to the new docs. I'll open a separate issue for this.

**Comment by jack-morrison** [comment]
> I'll open a separate issue for this.
Opened as #167 .

wrt the scope of this issue, I'll get links into the WML-CE section pointing the recording and slides.
