### ISSUE TITLE
Move Training Pages to New OLCF Docs

### ISSUE THREAD

**Issue by tom-papatheodore** [olcf/olcf-user-docs#167]
The ~~Tutorials,~~ Training Archive, and GPU Hackathons pages should be moved to OLCF docs, but the training calendar will still need to live on the OLCF page for now.

We will also need to decide how to link to training from the main OLCF site. Do we just point people to a main "Training" heading under FOR USERS -> OLCF User Docs (just like "System User Guides")? Or do we keep the individual links to the training sub-headings (e.g., Training Calendar, Training Archive, etc.)? If the latter, we break consistency with the way we link to the rest of the OLCF docs under the main FOR USERS heading in the main menu. If the former, users will need to e.g., jump from the OLCF site to the OLCF docs, then back to OLCF site for the training calendar. And similar for the Vimeo channel. 

I'm personally leaning toward the latter approach. Any opinions?

**Comment by jack-morrison** [comment]
If we set links on olcf.ornl.gov to open in new tabs/windows, the “multi-site problem” shouldn’t be too bad.

**Comment by jack-morrison** [comment]
Tutorials live at https://github.com/olcf-tutorials. The Training Archive and GPU Hackathons were added in #184 and #188. This can be closed.
