### ISSUE TITLE
Nsight Compute should be documented as in the NVIDIA profiler section

### ISSUE THREAD

**Issue by maxpkatz** [olcf/olcf-user-docs#174]
Nsight Compute now works on IBM Power systems as of CUDA 10.1 Update 1, there should be a description of how to use it for kernel-level profiling in the profilers section.

Related to #60.

**Comment by grahamlopez** [comment]
Indeed. I think that @gmarkomanolis has some recent presentation material/slides about this that we can hopefully leverage and convert.

**Comment by gmarkomanolis** [comment]
The slides were from Jeff https://www.olcf.ornl.gov/wp-content/uploads/2019/08/NVIDIA-Profilers.pdf but the plan was to just touch the topic as back then nsight was not available on Summit. However, there are not detailed instructions there.

**Comment by maxpkatz** [comment]
I'm volunteering to contribute this material, just marking this down for later.
