### ISSUE TITLE
Add info on backgrounding jsrun with the `--immediate` flag

### ISSUE THREAD

**Issue by jack-morrison** [olcf/olcf-user-docs#179]
backgrounding `jsrun` can be done with the usual `<thing to background> &` but it has its own `--immediate` option that's preferable to `&` + `wait`.

Also mention how many `jsrun`s can be launched before things break down due to per-node user process limits (4096 proc/user/batch node).

**Comment by chrisfuson** [comment]
We should also note --imediate's default behavior to send std out/err to /dev/null without using the --stdio_stdout (-o), --stdio_stderr (-k) options.
