### ISSUE TITLE
Run a RST linter

### ISSUE THREAD

**Issue by jack-morrison** [olcf/olcf-user-docs#20]
It would be nice to catch syntax errors as early as possible.

**Comment by grahamlopez** [comment]
I’m not sure. Contributors and reviewers need to build the docs for themselves, and I don’t want people to think that an automated linting check is an acceptable substitute.

**Comment by jack-morrison** [comment]
Fair point -- It will just be UA merging into this, anyways, and we'll all be building these locally. Closing for now. If at some point in the future this is desirable, we can revisit then.
