### ISSUE TITLE
Possibility of webhooks to push to production

### ISSUE THREAD

**Issue by mpbelhorn** [olcf/olcf-user-docs#21]
Currently, the OLCF internal K8 cluster polls every few minutes to check for changes.

I suspect it's possible to setup a webook or some other CI/DevOps process to trigger a rebuild on the K8 cluster when a PR is merged into the master branch. We should look into those options and what sort of security and credential management we'd need to do that with a public GitHub repo and a closed-access internal K8 cluster.

**Comment by grahamlopez** [comment]
Yeah, this might be possible. I opted for fewer moving pieces (that can break), but if this is a pain point, I am willing for someone else to do the homework.
We can also increase the polling frequency.

**Comment by mpbelhorn** [comment]
Due to the walled-garden nature of the OLCF K8 cluster, it is not possible to push webhooks from GitHub without complex mirroring of this repo using enterprise editions of at least two VCS systems. I won't leave the details here in a public forum, but regardless, we only have one of the necessary enterprise licenses and the features that could be used to do this are still experimental. Therefore, using webhooks to push to production is, at this time, much more complicated and less reliable than the current simple polling approach and won't likely be an improvement over the current approach.
