### ISSUE TITLE
Manually add external link icon to menu items

### ISSUE THREAD

**Issue by tom-papatheodore** [olcf/olcf-user-docs#215]
On the main training landing page (https://docs.olcf.ornl.gov/training/index.html), the links properly show the "external link" icon. However, the corresponding links in the menu do not. This breaks our standard to always show when users are being directed away from the docs.

NOTE: If you embed e.g., a unicode arrow, the arrow does show up in the menu, however, the links on the landing page include both the correct icon and the arrow - so this is no good.

**Comment by jack-morrison** [comment]
With `_static/{css,js}/` we should be able to write some javascript that looks for the presence of `http` or `https` in the menu l2 `href`s and give them a custom CSS class include a FontAwesome external icon `::after`

([link to icon](https://fontawesome.com/icons/external-link-alt?style=solid))

**Comment by jack-morrison** [comment]
It would be best to do this for all levels of the main nav, not just the training section.

**Comment by grahamlopez** [comment]
This exact issue is why I avoided putting external links in the navigation for the training to begin with.

**Comment by jack-morrison** [comment]
I think with a little bit of custom JS/CSS we can handle this one. I'm up to give it a try.
