### ISSUE TITLE
Mild clarity issue in NVMe Usage Example

### ISSUE THREAD

**Issue by secondspass** [olcf/olcf-user-docs#297]
There are some issues with clarity in the NVMe Usage Example section:

- there is a reference to test_nvme.sh, which is not used at all in the example batch script
- There is a **Job submssion script: check_nvme.lsf.** in bold in the middle of the paragraph (presumably this was meant to be the title of the code block below the paragraph)
- In the table comparing job scripts that use GPFS vs NVMe, there is no explanation of what `NAS-BTIO`, `btio`, and `input*` refer to. I can understand based on context clues that maybe `input*` refers to files that `btio` will write to, or something like that. But a small note explaining that might be helpful.

If you can provide some info on this, especially the third point, I can submit a pull request with these fixed. 

These docs are pretty awesome otherwise!

**Comment by gmarkomanolis** [comment]
- I think the .sh should be .lsf

- Yes, sometimes the text are merge from various other texts. 
- NAS BTIO was used for the example, you can find more information: http://www.softeng.rl.ac.uk/st/archive/SoftEng/SESP/Publications/paraio/paraio/node8.html  and https://www.nas.nasa.gov/assets/pdf/techreports/2003/nas-03-002.pdf. 

Something like:
BT-IO is part of the NAS parallel benchmark set, which is based on one of the computational kernels. The BT benchmark is based on a CFD code that uses an implicit algorithm to solve the 3D compressible Navier-Stokes equations. The benchmark requires an input file with the 3D dimensions as also the number of the timesteps for the solution.
