### ISSUE TITLE
Missing documentation link

### ISSUE THREAD

**Issue by porgull** [olcf/olcf-user-docs#33]
In the [`Common bsub Options` section](https://olcf-user-docs.granite.ccs.ornl.gov/systems/summit_user_guide.html#common-bsub-options), there is a link to `see the documentation` that does not exist.

**Comment by jack-morrison** [comment]
[[Link to section in RST](https://github.com/olcf/olcf-user-docs/blob/master/systems/summit_user_guide.rst#common-bsub-options)]

The IBM docs for `bsub` are really slim (or I can't find them). I recommend we change this to read:
```
...Note that LSF has numerous options; only the most common ones are described here. For more in-depth information about other LSF options, see the `bsub` man page.
```
