### ISSUE TITLE
:ref:batch-scripts is broken

### ISSUE THREAD

**Issue by grahamlopez** [olcf/olcf-user-docs#43]
The `batch-scripts` ref introduced by #34 has no destination.

**Comment by porgull** [comment]
I believe that is dependent one of the other PRs being merged; sorry, that was bad organization on me

**Comment by grahamlopez** [comment]
can you point to which one?

**Comment by porgull** [comment]
looks like #36

**Comment by grahamlopez** [comment]
confirmed fixed after #36 merged.
