### ISSUE TITLE
Identify and migrate relevant "Software Pages"

### ISSUE THREAD

**Issue by jack-morrison** [olcf/olcf-user-docs#5]
With this migration of OLCF docs into version control, we will be dropping the "[Software Pages](https://www.olcf.ornl.gov/for-users/software/)". 

However, there is a small set of software packages that have important documentation living in these pages. This issue is to identify which software packages should have their content migrated into this repository, and to make it happen.

Most likely, packages of interest are those that are vendor-provided and have vendor-provided site-specific accompanying documentation.

**Comment by jack-morrison** [comment]
### Definitely migrate
- ARM Performance Reports
- ARM Forge
  - DDT
- Vampir

### May make for good future additions
- Python (because it's a FAQ)
- Darshan (because it's loaded automatically via DefApps on Summit)
- Globus (because this is the recommended data transfer tool)

**Comment by grahamlopez** [comment]
just a note that needs a home:

there are references to compilers in the Rhea user-guide's "compiling" section that will need to be updated.

**Comment by jack-morrison** [comment]
@grahamlopez is that in the scope of this issue?

**Comment by grahamlopez** [comment]
I am talking about the links to e.g. the intel compilers, which seem to point to the old software page. Depending on how the software page gets redone, these kinds of links will either need to go away, or be updated, or ...

**Comment by mpbelhorn** [comment]
For transparency, I have a [WIP branch for some of these topics](https://github.com/mpbelhorn/olcf-user-docs/tree/belhorn/python_docs) (primarily focusing on Python, at the moment) in my fork of the repo. That branch re-instates a top-level software section with the intention of covering only site-specific guides, and less machine-specific information. It's also mostly just a broad skeleton layout for software documentation at the moment and can be expanded or trimmed back as desired.

Again, the only real content on it is the site-generalized python guide/faq. If we want to keep software docs in the machine guides as the above conversations suggest, then the python guide can be restructured however makes better sense. Though I'd like to avoid maintaining duplicate, overlapping docs on a software topic in multiple files/guides so a top-level software section (with reduced scope compared to what was on the wordpress site) make sense to me. Ie, just software guides with site-specific special sauce; not lists of software on each machine or descriptions of mundane common packages.

The contribution guide suggests that we keep personal branches out of this repo and only merge when ready. That said, If we wanted to go with a top-level/centralized software guide section, then I think we ought to keep the branch here to establish the core structure and outline, especially if others will be working on it simultaneously.

**Comment by jack-morrison** [comment]
@mpbelhorn @isubsmith Let's bump the priority of this, if we're able. Talking with @nickrf about getting ARM tools into the new docs, and it would be good to have structure in place that can be copied for vendors. (I'm thinking IBM WML like #125, too.)
