### ISSUE TITLE
Add job preemption details to Summit User Guide

### ISSUE THREAD

**Issue by jack-morrison** [olcf/olcf-user-docs#67]

**Comment by chrisfuson** [comment]
HPC Ops notes: https://confluence.ccs.ornl.gov/display/HPCTEAM/Summit+LSF+Preemption+Strategy

**Comment by chrisfuson** [comment]
Must use the killable queue.  Bins 4 and 5 eligible for pre-emption (by jobs in bins 1 and 2) once the bin's standard max walltime limit has been reached.  Max walltime for killable queue is 24 hours.  For example, in the killable queue a job in bin5 can request a walltime of 24 hours.  It will be eligible for pre-emption from a job in bin1 or bin2 after 2-hours of runtime.

Killable queue jobs requesting fewer than 91 nodes will be rejected at submission time by the submit filter.

**Comment by jack-morrison** [comment]
> Killable queue jobs requesting fewer than 91 nodes will be rejected at submission time by the submit filter.

@chrisfuson why would we want to exclude bin5 jobs from being preempt-able?
This doesn't seem to be in place:
```
$ bsub -q killable -W 10 -J test -nnodes 1 -PSTF007 -Is $SHELL
Job <649324> is submitted to queue <killable>.
<<Waiting for dispatch ...>>
<<Starting on batch4>>
```

**Comment by chrisfuson** [comment]
@jack-morrison node requests below 91 are eligible.  This should be bins 4 and 5. 

`summit-login5 237> bsub -q killable -W 10 -J test -nnodes 92 -PSTF007 -Is $SHELL

Batch job not submitted. Please address the following and resubmit:
--------------------------------------------------------------------

**  Requested nodes (92) over limit.  Please resubmit with a node count below 91.

------------------------------------------------------------------
Please contact help@olcf.ornl.gov if you need assistance.

Request aborted by esub. Job not submitted.
summit-login5 238>`
