### ISSUE TITLE
Add info on NVMe NFS caching to Summit User Guide

### ISSUE THREAD

**Issue by jack-morrison** [olcf/olcf-user-docs#69]
Starting w/ Sept. 24 outage - 100GB of each compute node's NVMe device will be dedicated to NFS cache to hold default libs. This should improve launch times. It also limits user-writable space on the burst buffer to ~~1500GB~~ 1400GB (down from ~~1600~~ 1500).

**Comment by gmarkomanolis** [comment]
I changed the text here: https://www.olcf.ornl.gov/for-users/system-user-guides/summit/summit-user-guide/#burst-buffer. Not sure if I should add on top with "important notice".

**Comment by jack-morrison** [comment]
Not sure it’s “important notice” worthy. Most aren’t maxing out NVMe

**Comment by chrisfuson** [comment]
100GB of each compute node's NVMe device is dedicated to NFS cache to help speed access to commonly used libraries from /sw.  When calculating maximum storage size, this cache and system overhead should be considered. We recommend a maximum storage of 1,400GB.

**Comment by jack-morrison** [comment]
Depends on #54
