### ISSUE TITLE
Add a `Getting Help` section

### ISSUE THREAD

**Issue by jack-morrison** [olcf/olcf-user-docs#70]
Best practices for getting support:

-- see comments below

**Comment by chrisfuson** [comment]
Can I suggest: 

Support best practices:
- Where possible, details are helpful and can help speed the process.  For example: Project ID, relevant directories, job scripts, jobIDs, modules at compile/runtime, host name.
- When replying to a ticket, keeping the ticket system's auto-generated subject the same will add content to the existing ticket; altering the subject will create a new ticket.  
- Maintaining a topic per ticket and opening a new ticket for new issues will help us better organize and speed response.  
- MOST IMPORTANT: do not hesitate to contact us, we will work through the details.

**Comment by grahamlopez** [comment]
> When replying to a ticket, keeping the ticket system's auto-generated subject the same will add content to the existing ticket; altering the subject will create a new ticket.

I had to read this a couple times. How about just:
- When replying to a ticket, do not modify the subject line.

> Maintaining a topic per ticket and opening a new ticket for new issues will help us better organize and speed response.

This is vague. I liked Jack's specificity from before, but motivated only by the effects on the users, not for us.
- Please do not open multiple tickets on the same unresolved topic. Doing so can fragment resources and slow down the time to resolution.
- Please do not respond to previous tickets with new, unrelated issues. This can slow down response time, make finding relevant information harder thereby slowing down time to resolution.

**Comment by jack-morrison** [comment]
> MOST IMPORTANT: do not hesitate to contact us, we will work through the details.

I agree with @chrisfuson that we could use some language like this ^.

**Comment by grahamlopez** [comment]
added this to the PR
