### ISSUE TITLE
"Connecting" - initial conversion or rewrite

### ISSUE THREAD

**Issue by grahamlopez** [olcf/olcf-user-docs#9]
This is a top-level section, and also needs to be linked to in the relevant places in the system user guides, and elsewhere as appropriate.

**Comment by grahamlopez** [comment]
there is currently a brief "Connecting for the first time" section under "Getting started." This could be used as a starting point, and should eventually just link to the possibly more thorough top-level page.

**Comment by isubsmith** [comment]
Fixed in PR #55.
