### ISSUE TITLE
consolidate to gpfs and/or alpine

### ISSUE THREAD

**Issue by grahamlopez** [olcf/olcf-user-docs#99]
Currently we have several ways of referring to this filesystem. Let's limit it to at most 2, and one if we could agree on it.

**Comment by gmarkomanolis** [comment]
As officially is not GPFS (we just mention it as more people know what is GPFS), we should call it either Spectrum Scale, or Alpine.

**Comment by grahamlopez** [comment]
Well, as you say, more people know what GPFS is.

**Comment by gmarkomanolis** [comment]
"Before 2015, Spectrum Scale was known as IBM General Parallel File System (GPFS)". Moreover they call the software from version 4 and later Spectrum Scale and before that version, GPFS. So, technically, GPFS is an older version without explanation that we call it GPFS just because people are familiar.

**Comment by grahamlopez** [comment]
I understand all of that. Let's discuss in group meeting with everyone.

**Comment by grahamlopez** [comment]
consider that "gpfs" is in all of the paths, and so we have to keep it in all of the code snippets and tables.

**Comment by jack-morrison** [comment]
Looking through the docs, I don't actually find this to be much of a problem. I can't remember ever seeing end-user confusion on this topic. The relevant paths in code snippets and tables include both "GPFS" and "Alpine" (`/gpfs/alpine/...`). This makes "Spectrum Scale," which is arguably the most correct name, the one least frequently used in docs and by users/staff.

There are a few places where we could make the tables more consistent. The `Type` field at these locations could read just "Spectrum Scale" to match the other tables in `/data` and `/accounts`:
```
./data/policies.rst:23
./data/policies.rst:25
./data/policies.rst:27
```

**Comment by jack-morrison** [comment]
d94f718f8fdf1b13f690606a57ae6371809b9598 did a good job of touching up the way we present filesystems in the docs.
